New plublic realese 1.4.3
nethesis/nethcti-app-iphone pull request #36
Opened 2022-08-31 14:57 UTC by marcospina1

1.4.3
• The user group selected last time in the Presence is kept set
• Removed the wording GROUPS and leave only the name of the group in the Presence
• Added the translation of the number into a name on call from the directory, keypad and presence
• Added a warning message during logout
1.4.2
• Fix device id registration
1.4.1
• In this version the crash on calling from the phone book has been fixed
1.4.0
• Presence section added
• Added the ability to disconnect the app through a specific presence status
• Added the link in the Dashboard to the new Presence section

2022-08-31 15:11 UTC, gsanchietti requested changes
Thank you for pushing this.

The app is still on production, so it doesn't make sense a real review of the code right now.
From a formal point of view, the commit history is a quite a mess and in Italian.
Still, I really appreciate the effort about an English recap inside the PR description.

Please also translate the `CHANGELOG,md` file.
After, if @SebastianMB-IT approves it, I'd go with a squash&merge to discard all useless commit messages.

2022-08-31 15:47 UTC, marcospina1 commented on CHANGELOG.md
> +- Sotituito il collegamento nella Dashboard alla nuova sezione Presence
No problem.. Thanks for your feedback!

2022-09-01 07:43 UTC, gsanchietti approved these changes
Ok for me, thank you @marcospina1 !

2022-09-01 12:31 UTC, SebastianMB-IT approved these changes

2022-09-01 12:56 UTC, merged